### ISSUE TITLE
Make executable jar OS independent

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs-5666-scatt-gp#18]
- [x] Look into NullPointerException when run on Windows - no longer exists
- [x] Research fully executable .jar via double click
- [ ] Test on clean Windows 7, clean Windows 10 (school system OS), and clean OSX

**Comment by KaraBeason** [comment]
NullPointerException no longer exists as of Michelle's changes on branch "metrics" that is about to be merged.

**Comment by KaraBeason** [comment]
@haietza @caldwellc1 After looking into it some more, I do not see a way of getting around having to have the json_simple.jar in the same directory as scatt.jar.
some refs:
http://stackoverflow.com/questions/1491990/how-to-create-an-executable-jar-with-dependancy-jars
http://stackoverflow.com/questions/9395207/how-to-include-jar-files-with-java-file-and-compile-in-command-prompt

## So current status of this issue as it stands: 

- We could deploy it as a zip file available for download in our repo, so the user could download this zip which would contain Scatt.jar, json_simple.jar
  - We have a few options here as far as making it a little neater
    - we could put json_simple.jar in a depndencies folder so it's not as cluttered at the Scatt.jar level
    - we could have two separate .zips available - Mac OS and Windows
      - Windows would contain the .bat file for the user to double click and run scatt
      - Mac OS would just be Scatt.jar and the dependencies folder.  User *should* be able to just double click Scatt.jar, but I need to test this on a Mac!
      - Could include a readme.txt with both that tells user how to execute Scatt (in addition to demo instructions in repo)
  - Specify the JRE version needed to run scatt in instructions.
- I personally think that we should close this issue, I could make a page in the wiki detailing the status of deployment, and we could drop an issue in our backlog to nail down our deployment strategy in a later iteration (idk because not many left).  I feel my time would be better spent helping with development, but I am very open to your input (and the client's)!

## Let me know your thoughts!  Thanks :)

**Comment by haietza** [comment]
@KaraBeason I agree - I think, while this will be an important piece for the overall application, it does not seem to be as high of a priority as the calculation and evaluation pieces. Instead of closing this issue, why don't we just move it into the Backlog list, remove it from the milestone, and remove you as the assignee? That way we'll have the history noted in the issue for when we (or the future developers working on the project) move it into a a future iteration.

**Comment by KaraBeason** [comment]
@haietza works for me!  I will do that now.
