### ISSUE TITLE
Merge Problem

### ISSUE THREAD

**Issue by caldwellc1** [JaysGitLab/cs-5666-scatt-gp#42]
@haietza @KaraBeason Ok so I merged the issue since there were only minor output changes and no code changes since the remove report.txt was already added. I fixed the conflicts in the report.java reportTest.java and the makefile.  I though it was good but after I merged I ran the code and it didn't compile. For some reason the Submission.java file on my branch was different from the master one, but they didn't merge together. This made methods such as  the get costume count for sprite not work since it no longer exist when merged. 
I think it pushed the changes up to master since I fixed the conflicts which is not want I really wanted after finding out it wasn't working. I'm not sure what to do since this is a major problem. Can we revert back? Or should we add the methods in Submission from the one on my branch?

**Comment by haietza** [comment]
@KaraBeason @caldwellc1 I reverted master back to the last commit (Kara's) before Cydney pushed. Let's always be sure to wait for the pull request to officially be approved before we merge into master please :). Cydney there had been several pushes to master since you created this branch, so there probably were several merge conflicts that needed to be dealt with. I'll take a look at your branch and see if I can get them resolved and pushed up.
